### PR TITLE
AurianeCarronSubmission

### PR DESCRIPTION
**Pull request by AurianeCarron73**
I have added the Docker image submission_anomaly_detector_auriane.tar to the project.
Test and train files were not included.
I didn't include RUN pip install --upgrade pip RUN pip install -r requirements.txt in the Docker File because requirements.txt file is already included in the Docker image and will be used to install the necessary packages during evaluation.
I worked on the Zero-Shot CLIP model for anomaly detection.

### CODE REVIEW

**Comment by llleeeso** [comment]
Hello, @AurianeCarron73.

There are only Dockerfile,  README.md,  requirements.txt in your docker image.
Please check and update your PR. 

Thank you.

**Comment by AurianeCarron73** [comment]
Can I send you something by mail?

**Comment by AurianeCarron73** [comment]
I have an issue when I pull so the only way to send the project is by mail.
Sorry for the inconvenience. I worked on the Zero shot. Can you help me,
this is the file
 AISystem-2402.zip
<https://drive.google.com/file/d/1lLf7J8AxYammALYUvD9qZ1BfPNVpS2Vi/view?usp=drive_web>

**Comment by llleeeso** [comment]
Hello,  @AurianeCarron73.
Your submission must be in the form of a Docker image.  
Could you please create a Dockerfile in your `zeroshot-clip` folder and build a Docker image that includes only the `zeroshot-clip` folder?  

You can achieve this by using the `COPY` command in your Dockerfile like this:  
```dockerfile
WORKDIR /workspace
COPY . /workspace
```

Thank you.

**Comment by AurianeCarron73** [comment]
I'm sorry I don't understand, i have already a docker file in the final
project file

**Comment by llleeeso** [comment]
Your Docker image must include your code. 
However, it seems that none of your code files were included in the Docker image.
Please ensure that all necessary project files are properly added during the build process.
Thank you.

**Comment by AurianeCarron73** [comment]
[image: image.png]it's not that ?

**Comment by AurianeCarron73** [comment]
I'm sorry i tried my best look at my command, i think will not be able to
submit..

**Pull request closed without merging**
